# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v4

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.

name: Reject Push with Unallowed Files

on:
  push:
    branches:
      - '**'  # 全てのブランチを監視

jobs:
  check_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for unallowed files
        run: |
          # 許可されたファイルパターン以外のファイルが含まれているか確認
          if git diff --cached --name-only | grep -Ev '^Makefile$|\.c$|\.h$|\.yml$|^[^/]+/[^/]+\.c$|^[^/]+/[^/]+\.h$'; then
            echo "Error: Push includes unallowed files. Only Makefile, *.c, *.h, and *.yml files in root and subdirectories are allowed."
            exit 1
          fi
